### ISSUE TITLE
Font improvement suggestion

### ISSUE THREAD

**Issue by Sermus** [achimdoebler/UGUI#2]
I suggest we extend UG_FONT definition with two constants: offset and length. The reason is that if i needed an incomplete character set, for example just numbers, i wouldn't spend ROM space for keeping the rest of the characters. Offset and length means the font defines characters starting from ascii code "offset" and ending by "offset + length"

**Comment by achimdoebler** [comment]
OK, good idea, I'll add this feature.

**Comment by achimdoebler** [comment]
Has already been added by Andrey.
Thanks!
