### ISSUE TITLE
Font kerning support

### ISSUE THREAD

**Issue by jonasschnelli** [achimdoebler/UGUI#33]
Hi

Am I right that UG does not support font kerning? The thing where an `I` is smaller then an `O`. Does every letter uses the same width?

Is there some pre-work since I'm very likely going to implement that.

**Comment by jarekkt** [comment]
Well, check my tools to convert TTF fonts to 8 bit anti alliased fonts. And different letters use different width - at least that is what I can see from converter output. But as I know full font kerning is not supported ( if you think of it as support for combinations like  "AV"  )

**Comment by jonasschnelli** [comment]
Thanks!
Are you referring to https://github.com/AriZuu/ttf2ugui?
I'll dive deeper and report more precise.

**Comment by jarekkt** [comment]
Yes, that is the case

**Comment by jonasschnelli** [comment]
I concerted a font and the font width was perfectly identical to the mockup done on the PC.
Thanks. Closing.
